namespace Models.StaticData {
public class Street {
    public static string[] list = {
        "Abby Park Street",
        "Adelaide Avenue",
        "Airplane Avenue",
        "Airport Avenue",
        "Airport Street",
        "Andreas Avenue",
        "Arthur Street",
        "Auerbach Avenue",
        "Auburn Avenue",
        "Barn Street",
        "Bay Avenue",
        "Beatles Avenue",
        "Belby Road",
        "Bus Avenue",
        "California Street",
        "Camp Street",
        "Cavour Avenue",
        "Central Cesta",
        "Central Street",
        "China Avenue",
        "Communal Square",
        "Constitution Street",
        "Copper Street",
        "Corn Street",
        "Costume Street",
        "Cresson Crescent",
        "Danish Avenue",
        "Dean Avenue",
        "Delaware Avenue",
        "Delta Street",
        "Democracy Avenue",
        "Department Street",
        "Dimitri Street",
        "Dock Street",
        "Dubnitz Road",
        "Eastern Cestaand",
        "East Hills Avenue",
        "Easy Street",
        "Elgin Avenue",
        "Elisabeth Street",
        "Empire Avenue",
        "Eppink Square",
        "Farmers Lane",
        "Federation Avenue",
        "Federation Square",
        "Flower Avenue",
        "Forest Street",
        "Francis IIStreet",
        "Freedom Avenue",
        "French Street",
        "Galghard Road",
        "Gateway Street",
        "Glider Avenue",
        "Gold Street",
        "Greenpark Avenue",
        "Hazlett Avenue",
        "Hendrix Avenue",
        "Heritage Avenue",
        "Highway Avenue",
        "History Avenue",
        "Hospital Street",
        "Hotair Ballon Avenue",
        "Hurbadome Avenue",
        "Hurbanova Street",
        "Hurricane Avenue",
        "Ida Street",
        "Impressionist Avenue",
        "Industry Street",
        "Innovation Avenue",
        "Jamal Hustróva Street",
        "Jamesons Crossing",
        "Katrina Street",
        "King Arthur Istreet",
        "Kings Street",
        "Law Street",
        "Libertas Avenue",
        "Long Road Avenue",
        "Lucy Street",
        "Mandarin Park Lane",
        "Maple Street",
        "Marine Avenue",
        "Mayores Road",
        "Mc Crooke Avenue",
        "Medieval Street",
        "Mill Place",
        "Millstreetand",
        "Mitch Cromwood Avenue",
        "Monorail Street",
        "Museum Avenue",
        "Newhaven Avenue",
        "New Orleans Street",
        "Newport Street",
        "New Street",
        "Noble City Path",
        "Northern Abby Avenueand",
        "Ocean Avenue",
        "Oceana Sidestreet",
        "Old Port Avenue",
        "Old Wharf",
        "Overbanken Road",
        "Pauerbach Avenue",
        "Paul Hladovka Avenue",
        "Pazkolit Uskalie Avenue",
        "Peoples Avenue",
        "Pine Avenue",
        "Pine Street",
        "Plaza Street",
        "Poets Street",
        "Prachstreetand",
        "Prague Avenue",
        "Princess Avenue",
        "Quarry Avenue",
        "Queen Mary Elisabeth Alley",
        "Rail Avenue",
        "Railway Street",
        "River Side Road",
        "River Street",
        "Rome Avenue",
        "Sycamore Drive",
        "Sebastian Street",
        "School Street",
        "Shall Street",
        "Shopping Avenue",
        "Shopping Street",
        "Silver Street",
        "Sobrance Path",
        "Southern Abby Avenue",
        "Southern Avenue",
        "Southern Millstreet Avenue",
        "Southern Street",
        "Square Street",
        "State Avenue",
        "Stone Street",
        "Storm Alley",
        "Subway Street",
        "Swamp Street",
        "Swit Street",
        "Sylvania Avenue",
        "Technology Avenue",
        "Temmar Eastwood Avenue",
        "Theater Street",
        "Venice Street",
        "Vienna Street",
        "Vlackstreetand",
        "Walden Alley",
        "Wallstreet",
        "Waterlily Avenue",
        "Water Street",
        "Western Cesta",
        "William Street",
        "Woodstock Street",
        "Zosnul Street"
    };
}
}